# Generated by Django 4.1.2 on 2022-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backend',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
