databases:
  - name: djangoapi
    databaseName: djangoapi
    user: djangoapi

services:
  - type: web
    name: djangoapi
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djangoapi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djangoapi
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
        